language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
deploy:
  edge: true
  sudo: false
  provider: cloudfoundary
  username: sarathysrm@gmail.com
  password: Candyshop5*
  api: https://api.run.pivotal.io
  organization: sarathysrt_org
  space: development
  app: hackathon
  repo: ASTRO-HACKATHON/hackathon
  skip_cleanup: true
